
module.exports = {
   'Abstract': null,
   'Introduction': null,
   'History': null,
   'Bitcoin As A State Transition System': null,
   'Definitions, Formalization and Previous Work': null,
   '_PROTOCOL_ Protocol Components': null,
   'Formalization': null,
   'Existing Consensus Algorithms': null,
   'Formal Consensus Goals': null,
   'Irregular emission': null,
   'Hardcoded constants': null,
   'Bulky scripts': null,
   'The _PROTOCOL_ Technology': null,
   '_PROTOCOL_ Consensus Algorithm': null,
   'Elliptic curve parameters': null,
   'Terminology': null,
   'Unlinkable payments': null,
   'One-time ring signatures': null,
   'Standard _PROTOCOL_ transaction': null,
   'Egalitarian Proof-of-work': null,
   'Definition': null,
   'Transactions': null,
   'Confidential Transactions and OWAS': null,
   'Traceability of Transactions': null,
   'Untraceable Transactions': null,
   'Merging Transactions Across Blocks': null,
   'Timestamp Server': null,
   'Proof-of-Work': null,
   'Network': null,
   'Incentive': null,
   'Reclaiming Disk Space': null,
   'Simplified Payment Verification': null,
   'Combining and Splitting Value': null,
   'Privacy': null,
   'Mining': null,
   'Merkle Trees': null,
   'Alternative Blockchain Applications': null,
   'Scripting': null,
   '_PROTOCOL_ Accounts': null,
   'Messages and Transactions': null,
   '_PROTOCOL_ State Transition Function': null,
   'Code Execution': null,
   'Blockchain and Mining': null,
   'Token Systems': null,
   'Financial derivatives': null,
   'Identity and Reputation Systems': null,
   'Decentralized File Storage': null,
   'Decentralized Autonomous Organizations': null,
   'Further Applications': null,
   'Modified GHOST Implementation': null,
   'Fees': null,
   'Computation And Turing-Completeness': null,
   'Currency And Issuance': null,
   'Mining Centralization': null,
   'The proposed algorithm': null,
   'Smooth emission': null,
   'Difficulty': null,
   'Size limits': null,
   'Excess size penalty': null,
   'Transaction scripts': null,
   'Scalability': null,
   'The Bitcoin Blockchain Scalability Problem': null,
   'A Network of Micropayment Channels Can Solve Scalability': null,
   'Micropayment Channels Do Not Require Trust': null,
   'A Network of Channels': null,
   'Bidirectional Payment Channels': null,
   'The Problem of Blame in Channel Creation': null,
   'Creating an Unsigned Funding Transaction': null,
   'Spending from an Unsigned Transaction': null,
   'Commitment Transactions: Unenforcible Construction': null,
   'Commitment Transactions: Ascribing Blame': null,
   'Creating a Channel with Contract Revocation': null,
   'Sequence Number Maturity': null,
   'Timestop': null,
   'Revocable Commitment Transactions': null,
   'Redeeming Funds from the Channel: Cooperative Counterparties': null,
   'Creating a new Commitment Transaction and Revoking Prior Commitments': null,
   'Process for Creating Revocable Commitment Transactions': null,
   'Cooperatively Closing Out a Channel': null,
   'Bidirectional Channel Implications and Summary': null,
   'Hashed Timelock Contract (HTLC)': null,
   'Non-revocable HTLC Construction': null,
   'Off-chain Revocable HTLC': null,
   'HTLC when the Sender Broadcasts the Commitment Transaction': null,
   'HTLC when the Receiver Broadcasts the Commitment Transaction': null,
   'HTLC Off-chain Termination': null,
   'HTLC Formation and Closing Order': null,
   'Key Storage': null,
   'Blockchain Transaction Fees for Bidirectional Channels': null,
   'Pay to Contract': null,
   'The _PROTOCOL_ Network': null,
   'Decrementing Timelocks': null,
   'Payment Amount': null,
   'Clearing Failure and Rerouting': null,
   'Payment Routing': null,
   'Correctness': null,
   'Agreement': null,
   'Utility': null,
   'Simulation Code': null,
   'Risks': null,
   'Improper Timelocks': null,
   'Forced Expiration Spam': null,
   'Coin Theft via Cracking': null,
   'Data Loss': null,
   'Forgetting to Broadcast the Transaction in Time': null,
   'Inability to Make Necessary Soft-Forks': null,
   'Colluding Miner Attacks': null,
   'Block Size Increases and Consensus': null,
   'Use Cases': null,
   'Calculations': null,
   'Related works': null,
   'Literature review': null,
   'Discussion': null,
   'Questions and Intuition': null,
   'Future Research': null,
   'Conclusion': null,
   'References': {
      0: "W. Dai, \"b-money,\" http://www.weidai.com/bmoney.txt, 1998.",
      1: "",
      2: "H. Massias, X.S. Avila, and J.-J. Quisquater, \"Design of a secure timestamping service with minimal trust requirements,\" In 20th Symposium on Information Theory in the Benelux, May 1999.",
      3: "",
      4: "S. Haber, W.S. Stornetta, \"How to time-stamp a digital document,\" In Journal of Cryptology, vol 3, no 2, pages 99-111, 1991.",
      5: "",
      6: "D. Bayer, S. Haber, W.S. Stornetta, \"Improving the efficiency and reliability of digital time-stamping,\" In Sequences II: Methods in Communication, Security and Computer Science, pages 329-334, 1993.",
      7: "",
      8: "S. Haber, W.S. Stornetta, \"Secure names for bit-strings,\" In Proceedings of the 4th ACM Conference on Computer and Communications Security, pages 28-35, April 1997.",
      9: "",
      10: "A. Back, \"Hashcash - a denial of service counter-measure,\" http://www.hashcash.org/papers/hashcash.pdf, 2002.",
      11: "",
      12: "R.C. Merkle, \"Protocols for public key cryptosystems,\" In Proc. 1980 Symposium on Security and Privacy, IEEE Computer Society, pages 122-133, April 1980.",
      13: "",
      14: "W. Feller, \"An introduction to probability theory and its applications,\" 1957.",
      15: "",
      16: "Koinster, \"White Paper Generator,\" http://whitepaper.koinster.com, 2017.",
      17: "",
   }
};